# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: openai-end-to-end-baseline
metadata:
  template: openai-end-to-end-baseline@0.0.1-beta

# Infra section defines the infrastructure provisioning
infra:
  provider: bicep
  path: infra/bicep
  module: main-advanced

# Optional pipeline section for CI/CD
pipeline:
  provider: github

# Environment variables and settings
env:
  AZURE_ENV_NAME: dev
  AZURE_LOCATION: eastus
  AZURE_SUBSCRIPTION_ID: ""
  
# Optional hooks for custom scripts
hooks:
  postprovision:
    posix:
      run: echo "Infrastructure provisioned successfully"
    windows:
      run: echo "Infrastructure provisioned successfully"
