# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 1 - Deploy Infrastructure
run-name: 1 - Deploy Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepFile:
        description: Main Bicep File
        required: true
        default: 'main-advanced.bicep'
        type: choice
        options:
          - main-basic.bicep
          - main-advanced.bicep
      parameterFile:
        description: Parameter File
        required: true
        default: 'main-advanced.dynamic.bicepparam'
        type: string
      loginUsingClientSecret:
        description: Login using Client Secret?
        required: false
        default: false
        type: boolean
      stackAction:
        description: Stack Action
        required: false
        default: 'deploy'
        type: choice
        options:
          - deploy
          - status
          - rollback
          - delete
          
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: ${{ inputs.bicepFile }}
      parameterFile: ${{ inputs.parameterFile }}
      parameterFileReplaceTokens: 'true'
      deploymentMode: 'Incremental'
      runCreateInfra: true
      deployInResourceGroup: true
      loginUsingClientSecret: ${{ inputs.loginUsingClientSecret }}
      stackAction: 'deploy' # Options: deploy, status, rollback, delete (empty = ARM deployment)
