# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 1 - Deploy Infrastructure
run-name: 1 - Deploy Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepFile:
        description: Main Bicep File
        required: true
        default: 'main-advanced.bicep'
        type: choice
        options:
          - main-basic.bicep
          - main-advanced.bicep
      parameterFile:
        description: Parameter File
        required: true
        default: 'main-advanced.dynamic.bicepparam'
        type: string
      # Group deployment configuration settings into a JSON input to reduce inputs
      deployConfig:
        description: |
          JSON string with deployment configuration. Example:
          '{"createResourceGroup":true,"publicAccessEnabled":true,"createDnsZones":true,"addRoleAssignments":true,"deployAIHub":true,"runBuildDeployAPI":false}'
        required: false        
        type: string
        default: '{"createResourceGroup":true,"publicAccessEnabled":true,"createDnsZones":true,"addRoleAssignments":true,"deployAIHub":true,"runBuildDeployAPI":false}'
      loginUsingClientSecret:
        description: Login using Client Secret?
        required: false
        default: false
        type: boolean
      stackAction:
        description: Deployment Stack Action
        required: false
        default: 'deploy'
        type: choice
        options:
          - deploy
          - rollback
          - status
      workflowMode:
        description: 'Workflow Mode'
        required: false
        default: 'plan-and-deploy'
        type: choice
        options:
          - plan-only
          - plan-and-deploy          
          - deploy-only
          
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templateConfig: >
        {"templatePath":"./infra/bicep/","templateFile":"${{ inputs.bicepFile }}","parameterFile":"${{ inputs.parameterFile }}","parameterFileReplaceTokens":"true"}
      deployConfig: ${{ inputs.deployConfig }}
      loginUsingClientSecret: ${{ inputs.loginUsingClientSecret }}
      stackAction: ${{ inputs.stackAction }}
      workflowMode: ${{ inputs.workflowMode }}
