# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 1 - Deploy Infrastructure
run-name: 1 - Deploy Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }} ${{ vars.INSTANCE_NUMBER }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepFile:
        description: Main Bicep File
        required: true
        default: 'main-basic.bicep'
        type: choice
        options:
          - main-basic.bicep
          - main-advanced.bicep
      parameterFile:
        description: Parameter File
        required: true
        default: 'main-basic.dynamic.bicepparam'
        type: string
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      addRoleAssignments:
        description: Add Role Assignments?
        type: boolean
        default: true
      deployAPIM:
        description: Deploy APIM?
        type: boolean
        default: true
      runBuildDeployAPI:
        description: Build and Deploy API?
        required: false
        default: false
        type: boolean
      loginUsingClientSecret:
        description: Login using Client Secret?
        required: false
        default: false
        type: boolean
        
      # runBuildDeployUI:
      #   description: Build and Deploy UI
      #   required: false
      #   default: false
      #   type: boolean
      # publicAccessEnabled:
      #   description: Public Access Enabled?
      #   type: boolean
      #   default: true
      # createDnsZones:
      #   description: Create DNS Zones?
      #   type: boolean
      #   default: true

jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: ${{ inputs.bicepFile }}
      parameterFile: ${{ inputs.parameterFile }}
      parameterFileReplaceTokens: 'true'

      createResourceGroup: ${{ inputs.createResourceGroup }}
      addRoleAssignments: ${{ inputs.addRoleAssignments }}
      runBuildDeployAPI: ${{ inputs.runBuildDeployAPI }}
      deployAPIM: ${{ inputs.deployAPIM }}
      loginUsingClientSecret: ${{ inputs.loginUsingClientSecret }}

      deployAIHub: true
      publicAccessEnabled: true
      createDnsZones: false
      requestorName: ${{ github.actor }}