# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 1 - Deploy Infrastructure
run-name: 1 - Deploy ${{ inputs.bicepVersion }} Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepVersion:
        description: Version - Basic=public, Advanced=VNET
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - advanced
      appsToDeploy:
        description: Apps to Deploy
        default: API+UI
        type: choice
        options:
          - none
          - API
          - UI
          - API+UI
      bicepAction:
        description: Bicep Deploy Mode
        default: create
        type: choice
        options:
          - create
          - whatIf
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      addRoleAssignments:
        description: Add Role Assignments?
        type: boolean
        default: true
      deployAPIM:
        description: Deploy APIM?
        type: boolean
        default: true

        # armDeploymentMode:
      #   description: Bicep Deploy Mode
      #   default: Incremental
      #   type: choice
      #   options:
      #     - Incremental
      #     - Complete
      #     - Validation
      # useOldBicepTask:
      #   description: Use the old Deploy ARM Task?
      #   type: boolean
      #   default: true

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: 'main-${{ inputs.bicepVersion }}.bicep'
      parameterFile: 'main-${{ inputs.bicepVersion }}.bicepparam'
      parameterFileReplaceTokens: 'true'
      requestorName: ${{ github.actor }}
      createResourceGroup: ${{ inputs.createResourceGroup }}
      addRoleAssignments: ${{ inputs.addRoleAssignments }}
      deployAPIM: ${{ inputs.deployAPIM }}
      appsToDeploy: ${{ inputs.appsToDeploy }}
      bicepDeploymentMode: ${{ inputs.bicepAction }}
      # useOldBicepTask: ${{ inputs.useOldBicepTask }}
      # armDeploymentMode: ${{ inputs.armDeploymentMode }}
