# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 1 - Deploy Infrastructure
run-name: 1 - Deploy Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }} ${{ inputs.bicepFile }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepVersion:
        description: Bicep Version - basic or advanced? Basic is public, Advanced includes private networking features.
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - advanced
      # bicepFile:
      #   description: Main Bicep File
      #   required: true
      #   default: 'main-basic.bicep'
      #   type: choice
      #   options:
      #     - main-basic.bicep
      #     - main-advanced.bicep
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      addRoleAssignments:
        description: Add Role Assignments?
        type: boolean
        default: true
      deployAPIM:
        description: Deploy APIM?
        type: boolean
        default: true
      runBuildDeployAPI:
        description: Build and Deploy API?
        required: false
        default: false
        type: boolean
      loginUsingClientSecret:
        description: Login using Client Secret?
        required: false
        default: false
        type: boolean

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'

      templateFile: 'main-${{ inputs.bicepVersion }}.bicep'
      parameterFile: 'main-${{ inputs.bicepVersion }}.bicepparam'
      # templateFile: ${{ inputs.bicepFile }}
      # parameterFile: '${{ inputs.bicepFile }}param'
      parameterFileReplaceTokens: 'true'

      requestorName: ${{ github.actor }}
      createResourceGroup: ${{ inputs.createResourceGroup }}
      addRoleAssignments: ${{ inputs.addRoleAssignments }}

      runBuildDeployAPI: ${{ inputs.runBuildDeployAPI }}
      deployAPIM: ${{ inputs.deployAPIM }}
      loginUsingClientSecret: ${{ inputs.loginUsingClientSecret }}
