# ------------------------------------------------------------------------------------------------------------------------
# Action: Build and deploy all container app modules
# ----------------------------------------------------------------------------------------------------
# Note: in order to do multiple CA build/deploys, you need to change FW and login ONCE, otherwise
# it tends to have token refresh issues and fail on the second and third app
# ------------------------------------------------------------------------------------------------------------------------
name: 3 - Deploy Infra, Build, Deploy All Apps
run-name: 3 - Deploy Infra, Build, Deploy to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - fernando
          - preston
          - chris
          - matt
      bicepVersion:
        description: Version - Basic is public, Advanced includes private networking features.
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - advanced
      appsToDeploy:
        description: Apps to Deploy
        default: none
        type: choice
        options:
          - none
          - API
          - UI
          - API+UI
      loginMethod:
        description: Login Method?
        type: choice
        default: federated
        options:
          - federated
          - client-secret
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      addRoleAssignments:
        description: Add Role Assignments?
        type: boolean
        default: true
      runSecurityScan:
        description: 'Run Security Scan'
        required: false
        default: false
        type: boolean
      deployAPIM:
        description: Deploy APIM?
        type: boolean
        default: true
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - app/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

# ------------------------------------------------------------------------------------------------------------------------
env:
  # these are defined by the project itself, so they can stay here...
  ACR_REPO_NAME: 'aiapps'

  UI_APP_PATH: 'website/chatui'
  UI_ACR_APP_NAME: 'chatui'
  UI_PORT: '8080'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  template-env:
    # You can't pass environment variables to templates, so put them in outputs here that you CAN pass
    name: Template Env Variables
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployEnvironment }}
    outputs:
      PROJECT_ROOT: ${{ github.workspace }}
      ENV_CODE: ${{ inputs.deployEnvironment }}
      APP_NAME: ${{ vars.APP_NAME }}
      APP_NAME_NO_DASHES: ${{ vars.APP_NAME_NO_DASHES }}
      RESOURCE_GROUP_NAME: '${{ vars.RESOURCEGROUP_PREFIX }}-${{ inputs.deployEnvironment }}-${{ vars.GLOBAL_REGION_CODE }}-${{ vars.INSTANCE_NUMBER }}'

      ACR_NAME: '${{ vars.APP_NAME_NO_DASHES }}cr${{ inputs.deployEnvironment }}'
      ACR_REPO_NAME: ${{ env.ACR_REPO_NAME }}
      CONTAINER_APP_ENV_NAME: '${{ vars.APP_NAME_NO_DASHES }}-cae-${{ inputs.deployEnvironment }}'

      UI_CONTAINER_APP_NAME: 'ca-ui-${{ vars.APP_NAME_NO_DASHES }}-${{ inputs.deployEnvironment }}-${{ vars.INSTANCE_NUMBER }}'
      UI_APP_PATH: ${{ env.UI_APP_PATH }}
      UI_ACR_APP_NAME: ${{ env.UI_ACR_APP_NAME }}
      UI_PORT: ${{ env.UI_PORT }}

      API_CONTAINER_APP_NAME: 'ca-api-${{ vars.APP_NAME_NO_DASHES }}-${{ inputs.deployEnvironment }}-${{ vars.INSTANCE_NUMBER }}'
      API_APP_PATH: ${{ env.API_APP_PATH }}
      API_ACR_APP_NAME: ${{ env.API_ACR_APP_NAME }}
      API_PORT: ${{ env.API_PORT }}

    steps:
      - name: Set common environment variables
        id: set-env
        run: |
          echo "PROJECT_ROOT: ${{ github.workspace }}"
          echo "inputs.ENV_CODE: ${{ inputs.deployEnvironment }}"
          echo "vars.APP_NAME: ${{ vars.APP_NAME }}"
          echo "vars.APP_NAME_NO_DASHES: ${{ vars.APP_NAME_NO_DASHES }}"
          echo "AZURE_RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP_NAME }}"

          echo "ACR_REPO_NAME: ${{ env.ACR_REPO_NAME }}"

          echo "UI_APP_PATH: ${{ env.UI_APP_PATH }}"
          echo "UI_ACR_APP_NAME: ${{ env.UI_ACR_APP_NAME }}"
          echo "UI_PORT: ${{ env.UI_PORT }}"

  # ------------------------------------------------------------------------------------------------------------------------
  scan-code:
    name: Scan Code
    uses: ./.github/workflows/template-scan-code.yml
    if: inputs.runSecurityScan
    secrets: inherit
    permissions:
      actions: read
      contents: write
      checks: write
      security-events: write

  # ------------------------------------------------------------------------------------------------------------------------
  deploy-bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: 'main-${{ inputs.bicepVersion }}.bicep'
      parameterFile: 'main-${{ inputs.bicepVersion }}.bicepparam'
      parameterFileReplaceTokens: 'true'
      requestorName: ${{ github.actor }}
      createResourceGroup: ${{ inputs.createResourceGroup }}
      addRoleAssignments: ${{ inputs.addRoleAssignments }}
      deployAPIM: ${{ inputs.deployAPIM }}
      appsToDeploy: ${{ inputs.appsToDeploy }}
      loginMethod: ${{ inputs.loginMethod }}

  # ------------------------------------------------------------------------------------------------------------------------
  deploy-ui:
    name: Deploy UI ${{ inputs.deployEnvironment }} ${{ inputs.deployType }}
    uses: ./.github/workflows/template-aca-deploy.yml
    if: inputs.runBuildDeployUI
    needs:
      - template-env
    secrets: inherit
    with:
      ENV_CODE: ${{ needs.template-env.outputs.ENV_CODE }}
      RESOURCE_GROUP: ${{ needs.template-env.outputs.RESOURCE_GROUP_NAME }}
      CONTAINER_APP_ENV_NAME: ${{ needs.build-all.outputs.UI_APP_PATH }}
      CONTAINER_NAME: ${{ needs.template-env.outputs.UI_CONTAINER_APP_NAME }}
      ACR_NAME: ${{ needs.template-env.outputs.ACR_NAME }}
      IMAGE_NAME: ${{ needs.build-all.outputs.UI_IMAGE_NAME }}
      PORT: ${{ needs.template-env.outputs.UI_PORT }}

  # ------------------------------------------------------------------------------------------------------------------------
  deploy-api:
    name: Deploy API ${{ inputs.deployEnvironment }} ${{ inputs.deployType }}
    uses: ./.github/workflows/template-aca-deploy.yml
    if: inputs.runBuildDeployAPI
    needs:
      - template-env
    secrets: inherit
    with:
      ENV_CODE: ${{ needs.template-env.outputs.ENV_CODE }}
      RESOURCE_GROUP: ${{ needs.template-env.outputs.RESOURCE_GROUP_NAME }}
      CONTAINER_APP_ENV_NAME: ${{ needs.build-all.outputs.API_APP_PATH }}
      CONTAINER_NAME: ${{ needs.template-env.outputs.API_CONTAINER_APP_NAME }}
      ACR_NAME: ${{ needs.template-env.outputs.ACR_NAME }}
      IMAGE_NAME: ${{ needs.build-all.outputs.API_IMAGE_NAME }}
      PORT: ${{ needs.template-env.outputs.API_PORT }}

  # ------------------------------------------------------------------------------------------------------------------------
  # Deploy a Project inside the AI Foundry Hub
  # ------------------------------------------------------------------------------------------------------------------------
  deploy-hub-project:
    name: Deploy Hub Project ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-ai-hub-project-deploy.yml
    if: inputs.deployAIHub
    needs:
      - deploy-bicep
      - template-env
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      resourceGroupName: ${{ needs.template-env.outputs.RESOURCE_GROUP_NAME }}

  # # ------------------------------------------------------------------------------------------------------------------------
  # # Future use...!
  # # ------------------------------------------------------------------------------------------------------------------------
  # smoke-test:
  #   name: Smoke Test
  #   uses: ./.github/workflows/template-smoke-test.yml
  #   if: inputs.runSmokeTest
  #   needs: deploy-ui
  #   secrets: inherit
  #   permissions:
  #     contents: write
  #     issues: read
  #     checks: write
  #     pull-requests: read
  #   with:
  #     envCode: ${{ inputs.deployEnvironment }}
  #     testPath: 'playwright/ui-tests'
  #     testType: 'ui'
